version: '3'
services:
  postgresdb:
    image: postgres
    restart: always
    ports:
      - 5432:5432 
    environment:
      - POSTGRES_USER=postgresadmin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=test
    volumes:
      - db-data:/test/db
  pgadmin:
    image: dpage/pgadmin4
    restart: always
    ports:
      - 5050:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    depends_on:
      - postgresdb
  demo-app:
    image: pranjal698/server
    restart: always
    ports:
      - 3000:3000
    environment:
      - DB_USER=postgresadmin
      - DB_HOST=postgresdb
      - DB_DATABASE=test
      - DB_PASSWORD=password
      - DB_PORT=5432
    depends_on:
      - postgresdb
volumes:
  db-data:
    driver: local
