apiVersion: v1
kind: Namespace
metadata:
  name: my-namespace
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgresdb-configmap
  namespace: my-namespace
data:
  db_name: test

---
apiVersion: v1
kind: Secret
metadata:
  name: postgresdb-secret
  namespace: my-namespace
type: Opaque
data:
  username: cG9zdGdyZXNhZG1pbg==
  password: cGFzc3dvcmQ=
  pgadmin_email: YWRtaW5AZ21haWwuY29t
  pgadmin_password: YWRtaW4=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: my-namespace
  labels:
    app: postgresdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      namespace: my-namespace
      labels:
        app: postgresdb
    spec:
      containers:
      - name: postgresdb
        image: postgres
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgresdb-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresdb-secret
              key: password
        - name: POSTGRES_DB 
          valueFrom: 
            configMapKeyRef:
              name: postgresdb-configmap
              key: db_name

---
apiVersion: v1
kind: Service
metadata:
  name: postgresdb-service
  namespace: my-namespace
spec:
  selector:
    app: postgresdb
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin
  namespace: my-namespace
  labels:
    app: pgadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pgadmin
  template:
    metadata:
      namespace: my-namespace
      labels:
        app: pgadmin
    spec:
      containers:
      - name: pgadmin
        image: dpage/pgadmin4
        ports:
        - containerPort: 80
        env:
        - name: PGADMIN_DEFAULT_EMAIL
          valueFrom:
            secretKeyRef:
              name: postgresdb-secret
              key: pgadmin_email
        - name: PGADMIN_DEFAULT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgresdb-secret
              key: pgadmin_password
---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: my-namespace
spec:
  selector:
    app: pgadmin
  type: LoadBalancer  
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30005
