apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
  namespace: my-namespace
data:
  db_host: postgres

---
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: my-namespace
type: Opaque
data:
  username: fdS3dYxcFGb=
  password: bg3XsDbKrTv=

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
  namespace: my-namespace
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      namespace: my-namespace
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 8385
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: db_host
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: password

---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: my-namespace
spec:
  ports:
    - name: postgres
      port: 8385
      targetPort: 8385 
  selector:
    app: postgres

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgadmin-deployment
  namespace: my-namespace
spec:
  selector:
    matchLabels:
      app: pgadmin
  replicas: 1
  template:
    metadata:
      labels:
        app: pgadmin
    spec:
      containers:
        - name: pgadmin4
          image: dpage/pgadmin4
          env:
            - name: PGADMIN_DEFAULT_EMAIL
              value: "admin"
            - name: PGADMIN_DEFAULT_PASSWORD
              value: "password"
            - name: PGADMIN_PORT
              value: "8081"
          ports:
            - containerPort: 8081
              name: pgadminport

---
apiVersion: v1
kind: Service
metadata:
  name: pgadmin-service
  namespace: my-namespace
  labels:
    app: pgadmin
spec:
  selector:
    app: pgadmin
  type: LoadBalancer
  ports:
    - port: 8081
      targetPort: 8081
      nodePort: 3000