version: '3'
services:
  postgres:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
    volumes:
      - ./volume:/var/lib/postgresql/data  
  pgadmin4:
    image: "dpage/pgadmin4"
    restart: always
    ports:
      - 5555:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin
      - PGADMIN_DEFAULT_PASSWORD=password
      # Server is added in the pgadmin4 gui :)
  pgdb:
    image: akshith6212/pgdb:2.0
    restart: always
    ports:
      - 3000:3000
    depends_on:
      - postgres
