version: '3'

services:
    postgres:
        image: 'postgres:latest'
        ports:
            - 5435:5432
        restart: always
        environment: 
            POSTGRES_PASSWORD: 'postgres'
        volumes: 
            - ./volume:/var/lib/postgresql/data  
    
    pgadmin4:
        image: 'dpage/pgadmin4'
        restart: always
        ports: 
            - 8080:80
        depends_on:
            - postgres
        environment:
            PGADMIN_DEFAULT_EMAIL: 'admin'
            PGADMIN_DEFAULT_PASSWORD: 'password'

    server:
        image: 'shyamalshah/server'
        depends_on:
            - postgres 
        ports:
          - 3000:3000
    