apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mongo-express-ingres
  namespace: my-namespace
spec:
  rules:
    - host: abc.com
      http:
        paths:
          - path: /
            backend:
              serviceName: mongo-express-service
              servicePort: 8081